server:
  error:
    include-stacktrace: on-param

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics-api
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace